charlees/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

from products import urls as products_urls
from user import urls as auth_urls
from profiles import urls as profile_urls
from core import urls as core_urls
from products import urls as products_urls

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^user/', include(auth_urls, app_name='user', namespace='dj-auth')),
    url(r'^profile/', include(profile_urls)),
    url(r'^products/', include(products_urls)),
    url(r'^api/', include(core_urls)),
]  + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/urls.py
from django.conf.urls import url, include

from rest_framework.urlpatterns import format_suffix_patterns
from rest_framework_jwt.views import obtain_jwt_token

from profiles.api import views as profile_views
from user.api import views as user_views
from products.api import views as products_views



urlpatterns = [

    # products

    url(r'^products/(?P<pk>[0-9]+)/$', products_views.PrivateProductDetail.as_view()),
    url(r'^products/detail/(?P<key>[\w]{6})/$', products_views.PublicProductDetail.as_view()),

    # profile

    url(r'^profile/$', profile_views.ProfileView.as_view()),
    url(r'^profile/products/$', products_views.ProductsListView.as_view()),

    # user

    url(r'^users/$', user_views.UserList.as_view()),
    url(r'^users/create/$', user_views.UserCreate.as_view()),
    url(r'^users/(?P<pk>[0-9]+)/$', user_views.UserDetail.as_view()),
    url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    url(r'^api-token-auth/$', obtain_jwt_token),
]

urlpatterns = format_suffix_patterns(urlpatterns)

user/urls.py
from django.conf.urls import include, url
from django.contrib.auth import \
    views as auth_views
from django.contrib.auth.forms import \
    AuthenticationForm
from django.core.urlresolvers import reverse_lazy
from django.views.generic import (
    RedirectView, TemplateView)

from .views import (
    ActivateAccount, CreateAccount,
    DisableAccount, ResendActivationEmail)

password_urls = [
    url(r'^$',
        RedirectView.as_view(
            pattern_name='dj-auth:pw_reset_start',
            permanent=False)),
    url(r'^change/$',
        auth_views.password_change,
        {'template_name':
            'user/password_change_form.html',
         'post_change_redirect': reverse_lazy(
            'dj-auth:pw_change_done')},
        name='pw_change'),
    url(r'^change/done/$',
        auth_views.password_change_done,
        {'template_name':
            'user/password_change_done.html'},
        name='pw_change_done'),
    url(r'^reset/$',
        auth_views.password_reset,
        {'template_name':
            'user/password_reset_form.html',
         'email_template_name':
            'user/password_reset_email.txt',
         'subject_template_name':
            'user/password_reset_subject.txt',
         'post_reset_redirect': reverse_lazy(
            'dj-auth:pw_reset_sent')},
        name='pw_reset_start'),
    url(r'^reset/sent/$',
        auth_views.password_reset_done,
        {'template_name':
            'user/password_reset_sent.html'},
        name='pw_reset_sent'),
    url(r'^reset/'
        r'(?P<uidb64>[0-9A-Za-z_\-]+)/'
        r'(?P<token>[0-9A-Za-z]{1,13}'
        r'-[0-9A-Za-z]{1,20})/$',
        auth_views.password_reset_confirm,
        {'template_name':
            'user/password_reset_confirm.html',
         'post_reset_redirect': reverse_lazy(
            'dj-auth:pw_reset_complete')},
        name='pw_reset_confirm'),
    url(r'reset/done/$',
        auth_views.password_reset_complete,
        {'template_name':
            'user/password_reset_complete.html',
         'extra_context':
             {'form': AuthenticationForm}},
        name='pw_reset_complete'),
]

urlpatterns = [
    url(r'^$',
        RedirectView.as_view(
            pattern_name='dj-auth:login',
            permanent=False)),
    url(r'^activate/'
        r'(?P<uidb64>[0-9A-Za-z_\-]+)/'
        r'(?P<token>[0-9A-Za-z]{1,13}'
        r'-[0-9A-Za-z]{1,20})/$',
        ActivateAccount.as_view(),
        name='activate'),
    url(r'^activate/resend/$',
        ResendActivationEmail.as_view(),
        name='resend_activation'),
    url(r'^activate',
        RedirectView.as_view(
            pattern_name=(
                'dj-auth:resend_activation'),
            permanent=False)),
    url(r'^create/$',
        CreateAccount.as_view(),
        name='create'),
    url(r'^create/done/$',
        TemplateView.as_view(
            template_name=(
                'user/user_create_done.html')),
        name='create_done'),
    url(r'^disable/$',
        DisableAccount.as_view(),
        name='disable'),
    url(r'^login/$', auth_views.LoginView.as_view(template_name='user/login.html'), name='login'),
    url(r'logout/$', auth_views.logout,
        {'template_name': 'user/logged_out.html',
         'extra_context':
             {'form': AuthenticationForm}},
        name='logout'),
    url(r'^password/', include(password_urls)),
]

templates/site/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<!-- start title -->
 <title>
{% block title %}
   Charlees
{% endblock %}
 </title>
<!-- end title -->

<!-- start imports -->

    <!-- css -->
    <link rel="stylesheet" type="text/css" href="{% static 'site\css\bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'site\css\style.css' %}">
    {% block head_css %}
    {% endblock %}

    <!-- JavaScript -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.11.0/umd/popper.min.js" integrity="sha384-b/U6ypiBEHpOf/4+1nzFpr53nxSS+GLCkfwBdFNTxtclqqenISfwAzpKaMNFNmj4" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/js/bootstrap.min.js" integrity="sha384-h0AbiXch4ZDo7tp9hKZ4TsHbi047NrKGLO3SEJAg45jXxnGIfYzk4Si90RDIqNm1" crossorigin="anonymous"></script>
    <script src="https://use.fontawesome.com/3d066b17fd.js"></script>
    {% block head_js %}
    {% endblock %}

</head>
<!-- end imports -->
<body>
<nav class="navbar navbar-expand-lg" id="navbar-base">
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse center" id="navbarSupportedContent">
        <ul class="navbar-nav ml-auto">
            <li class="nav-item active">
                <a class="nav-link" href="{% url 'organizer_home' %}">Home <span
                        class="sr-only">(current)</span></a>
            </li>
            {% if user.is_authenticated %}
                <li class="nav-item">
                    <a class="nav-link my-2 my-sm-0" href="{% url 'profile' %}">&nbsp;
                        Mein Profil ({{ user.get_short_name }})</a>
                    <li class="nav-item">
                    <a class="nav-link my-2 my-sm-0" href="{% url 'dj-auth:logout' %}?next={{ request.path }}">&nbsp;
                        Logout</a>
                </li>
                </li>
            {% else %}
                <li class="nav-item">
                    <a class="nav-link my-2 my-sm-0" href="{% url 'dj-auth:login' %}?next={{ request.path }}">&nbsp;
                        Login</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link my-2 my-sm-0" href="{% url 'dj-auth:create' %}">&nbsp;
                        Registrieren</a>
                </li>
            {% endif %}
        </ul>
    </div>
</nav>
      {% if messages %}
        <div class="row">
          <div class="twelve columns">
            <ul class="messages">
              {% for message in messages %}
                {% if message.tags %}
                  <li class="{{ message.tags }}">
                {% else %}
                  <li>
                {% endif %}
                {{ message }}</li>
              {% endfor %}
        </ul></div></div>
      {% endif %}

{% block content %}

{% endblock %}

</body>
</html>