charlees/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

from products import urls as products_urls
from user import urls as auth_urls
from profiles import urls as profile_urls
from core import urls as core_urls
from products import urls as products_urls

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^user/', include(auth_urls, app_name='user', namespace='dj-auth')),
    url(r'^profile/', include(profile_urls)),
    url(r'^products/', include(products_urls)),
    url(r'^api/', include(core_urls)),
]  + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/urls.py
from django.conf.urls import url, include

from rest_framework.urlpatterns import format_suffix_patterns
from rest_framework_jwt.views import obtain_jwt_token

from profiles.api import views as profile_views
from user.api import views as user_views
from products.api import views as products_views



urlpatterns = [

    # products

    url(r'^products/(?P<pk>[0-9]+)/$', products_views.PrivateProductDetail.as_view()),
    url(r'^products/detail/(?P<key>[\w]{6})/$', products_views.PublicProductDetail.as_view()),

    # profile

    url(r'^profile/$', profile_views.ProfileView.as_view()),
    url(r'^profile/products/$', products_views.ProductsListView.as_view()),

    # user

    url(r'^users/$', user_views.UserList.as_view()),
    url(r'^users/create/$', user_views.UserCreate.as_view()),
    url(r'^users/(?P<pk>[0-9]+)/$', user_views.UserDetail.as_view()),
    url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    url(r'^api-token-auth/$', obtain_jwt_token),
]

urlpatterns = format_suffix_patterns(urlpatterns)

profiles/urls.py
from django.conf.urls import url, include
from .views import (ProfileDetail, ProfileUpdate, PublicProfileDetail)

urlpatterns = [
    url(r'^profile/$',
        ProfileDetail.as_view(),
        name='profile'),
    url(r'^profile/edit/$',
        ProfileUpdate.as_view(),
        name='profile_update'),
    url(r'^profile/public/(?P<slug>[\w\-]+)/$',
        PublicProfileDetail.as_view(),
        name='public_profile'),
]

user/urls.py
from django.conf.urls import include, url
from django.contrib.auth import \
    views as auth_views
from django.contrib.auth.forms import \
    AuthenticationForm
from django.core.urlresolvers import reverse_lazy
from django.views.generic import (
    RedirectView, TemplateView)

from .views import (
    ActivateAccount, CreateAccount,
    DisableAccount, ResendActivationEmail)

password_urls = [
    url(r'^$',
        RedirectView.as_view(
            pattern_name='dj-auth:pw_reset_start',
            permanent=False)),
    url(r'^change/$',
        auth_views.password_change,
        {'template_name':
            'user/password_change_form.html',
         'post_change_redirect': reverse_lazy(
            'dj-auth:pw_change_done')},
        name='pw_change'),
    url(r'^change/done/$',
        auth_views.password_change_done,
        {'template_name':
            'user/password_change_done.html'},
        name='pw_change_done'),
    url(r'^reset/$',
        auth_views.password_reset,
        {'template_name':
            'user/password_reset_form.html',
         'email_template_name':
            'user/password_reset_email.txt',
         'subject_template_name':
            'user/password_reset_subject.txt',
         'post_reset_redirect': reverse_lazy(
            'dj-auth:pw_reset_sent')},
        name='pw_reset_start'),
    url(r'^reset/sent/$',
        auth_views.password_reset_done,
        {'template_name':
            'user/password_reset_sent.html'},
        name='pw_reset_sent'),
    url(r'^reset/'
        r'(?P<uidb64>[0-9A-Za-z_\-]+)/'
        r'(?P<token>[0-9A-Za-z]{1,13}'
        r'-[0-9A-Za-z]{1,20})/$',
        auth_views.password_reset_confirm,
        {'template_name':
            'user/password_reset_confirm.html',
         'post_reset_redirect': reverse_lazy(
            'dj-auth:pw_reset_complete')},
        name='pw_reset_confirm'),
    url(r'reset/done/$',
        auth_views.password_reset_complete,
        {'template_name':
            'user/password_reset_complete.html',
         'extra_context':
             {'form': AuthenticationForm}},
        name='pw_reset_complete'),
]

urlpatterns = [
    url(r'^$',
        RedirectView.as_view(
            pattern_name='dj-auth:login',
            permanent=False)),
    url(r'^activate/'
        r'(?P<uidb64>[0-9A-Za-z_\-]+)/'
        r'(?P<token>[0-9A-Za-z]{1,13}'
        r'-[0-9A-Za-z]{1,20})/$',
        ActivateAccount.as_view(),
        name='activate'),
    url(r'^activate/resend/$',
        ResendActivationEmail.as_view(),
        name='resend_activation'),
    url(r'^activate',
        RedirectView.as_view(
            pattern_name=(
                'dj-auth:resend_activation'),
            permanent=False)),
    url(r'^create/$',
        CreateAccount.as_view(),
        name='create'),
    url(r'^create/done/$',
        TemplateView.as_view(
            template_name=(
                'user/user_create_done.html')),
        name='create_done'),
    url(r'^disable/$',
        DisableAccount.as_view(),
        name='disable'),
    url(r'^login/$', auth_views.LoginView.as_view(template_name='user/login.html'), name='login'),
    url(r'logout/$', auth_views.logout,
        {'template_name': 'user/logged_out.html',
         'extra_context':
             {'form': AuthenticationForm}},
        name='logout'),
    url(r'^password/', include(password_urls)),
]

products/models.py
import uuid as uuid_lib

from django.db import models
from django.conf import settings
from django.core.urlresolvers import reverse
from django.utils.text import slugify


class Product(models.Model):
    BIKE = 'BK'
    ELECTRONIC = 'EL'
    CAR = 'CA'
    OTHER = 'OT'
    PRODUCT_TYPE_CHOICES = (
        (BIKE, 'BIKE'),
        (ELECTRONIC, 'TECHNIK'),
        (CAR, 'AUTO'),
        (OTHER, 'ANDERE'),
    )
    OWNED = 'OW'
    STOLEN = 'NO'
    PRODUCT_STATUS_CHOICES = (
        (OWNED, 'OWNED'),
        (STOLEN, 'STOLEN')
    )
    register_date = models.DateTimeField(auto_now_add=True)
    zip_code = models.CharField(max_length=6)
    key = models.CharField(max_length=6, unique=True)
    slug = models.SlugField(max_length=31, unique=True, blank=True, help_text='A label for the URL config')
    type = models.CharField(max_length=2, choices=PRODUCT_TYPE_CHOICES, default=BIKE)
    status = models.CharField(max_length=2, choices=PRODUCT_STATUS_CHOICES, default=OWNED)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, related_name='products', on_delete=models.CASCADE)
    is_blocked = models.BooleanField(default=False) # if product has be found within the last hours/days
    for_sale = models.BooleanField(default=False)
    uuid = models.UUIDField(db_index=True, default=uuid_lib.uuid4, editable=False)

    def save(self, *args, **kwargs):
        self.slug = slugify(self.type + self.key)
        super(Product, self).save(*args, **kwargs)

    class Meta:
        ordering = ['register_date']

    def __str__(self):
        return self.slug

    def get_absolute_url(self):
        return reverse('product_detail', kwargs = {'slug': self.slug})

profiles/models.py
import uuid as uuid_lib

from django.db import models
from django.conf import settings
from django.core.urlresolvers import reverse



class ProfileManager(models.Manager):

    def get_by_natural_key(self, slug):
        return self.get(slug=slug)


class Profile(models.Model):
    user = models.OneToOneField(settings.AUTH_USER_MODEL)
    slug = models.SlugField(max_length=30, unique=True, blank=True)
    about = models.TextField()
    joined = models.DateTimeField("Date Joined", auto_now_add=True)
    img = models.ImageField(upload_to='profiles/profile_pictures',
                            default='/profiles/profile_pictures/default_profile_picture.png')
    uuid = models.UUIDField(db_index=True, default=uuid_lib.uuid4, editable=False)
    objects = ProfileManager()

    def __str__(self):
        return self.user.get_username()

    def get_absolute_url(self):
        return reverse('profile')

    def get_update_url(self):
        return reverse('profile_update')

    def natural_key(self):
        return (self.slug,)
    natural_key.dependencies = ['user.user']

profiles/api/views.py
from django.http import Http404

from rest_framework.views import APIView

from ..models import Profile
from .serializer import ProfileSerializer


from rest_framework import generics, permissions
from rest_framework.response import Response


class ProfileView(APIView):
    """
    Retrieve profile Information - only GET is allowed on this view
    """
    def get_object(self, request):
        try:
            return Profile.objects.get(user=request.user)
        # add prefetch and select prefetch to optimise database here
        # this to add database optimisation there is an formulated method here
        except Profile.DoesNotExist:
            raise Http404

    def get(self, request, format=None):
        profile = self.get_object(request)
        serializer = ProfileSerializer(profile)
        return Response(serializer.data)

profiles/views.py
from django.views.generic import UpdateView, DetailView

from user.decorators import class_login_required
from .utils import ProfileGetObjectMixin
from .models import Profile





@class_login_required
class ProfileDetail(
        ProfileGetObjectMixin, DetailView):
    model = Profile

class PublicProfileDetail(DetailView):
    model = Profile

@class_login_required
class ProfileUpdate(
        ProfileGetObjectMixin, UpdateView):
    fields = ('about',)
    model = Profile
    template_name = 'profiles/profile_form_update.html'

profiles/templates/profiles/base_profiles.html
{% extends partent_template|default:'site/base.html' %}

profiles/templates/profiles/profile_detail.html
{% extends parent_template|default:"profiles/base_profiles.html" %}

{% load static %}

{% block head_css %}
    <link rel="stylesheet" type="text/css" href="{% static 'profiles\css\style.css' %}">
{% endblock %}

{% block title %}
    {{ block.super }} -
    {{ profile.user.get_full_name }}'s Profile
{% endblock %}

{% block content %}
    <!-- personal section -->
    <section id="profile-base">
        <div class="container">

                <div class="profile-overview">
                    <div class="row">
                        <div class="col-sm-4 profile-img-box">
                            <img src="{{ profile.img.url }}.png" alt="" class="rounded-circle" id="profile_img">
                        </div>
                        <div class="col-sm-8 short-data">
                            <div class="row">
                                div.col
                            </div>

                        </div>
                </div>
            </div>
            <div class="row">
                <div class="card text-center profile-card">
                    <div class="card-header profile-card-header">
                        {{ profile.user.get_short_name|title }}s Profil
                    </div>
                    <div class="card-block">
                        <h4 class="card-title">Special title treatment</h4>
                        <p class="card-text">With supporting text below as a natural lead-in to additional content.</p>
                        <div class="profile-edit">
                        <div class="row">
                            <div class="col-sm-4">
                                <a href="{{ profile.get_update_url }}"><i class="fa fa-pencil-square-o" aria-hidden="true"></i> Text bearbeiten</a>
                            </div>
                            <div class="col-sm-4">
                                <a href=""><i class="fa fa-picture-o" aria-hidden="true"></i> Profilbild ändern</a>
                            </div>
                            <div class="col-sm-4">
                                <a href=""><i class="fa fa-user-o" aria-hidden="true"></i> Profil Bearbeiten</a>
                            </div>
                        </div>
                            </div>
                    </div>
                </div>
            </div>

            <div class="row">
            <p><i class="fa fa-chevron-circle-down" aria-hidden="true"></i> <br></nr>Zu deinen Produkten</p>
        </div>
        </div>

    </section>

    {% comment %}
                <div class="dropdown-menu" aria-labelledby="dropdownMenuLink">
                    <a class="dropdown-item" href="{{ profile.get_update_url }}">Profil bearbeiten</a>
                    <a class="dropdown-item" href="{% url 'dj-auth:pw_change' %}">Passwort ändern</a>
                    <a class="dropdown-item" href="{% url 'dj-auth:disable' %}">Konto deaktivieren</a>
                </div>

            <!-- profile img -->
            <div class="container justify-content-center" style="text-align: center">
                <img src="{{ profile.img.url }}.png" alt="" class="rounded-circle" id="profile_img">
                <h2>{{ profile.user.get_full_name }}</h2>
            </div>

            <div class="container">
                <div class="row justify-content-center">
                    <div class="col-sm-5 card bg-primary text-center">
                        <blockquote class="blockquote mb-0">
                            {% if profile.about %}
                                <p>"{{ profile.about|linebreaks }}"</p>
                            {% else %}
                                <p>Schreib doch etwas über dich! Stößt jemand auf einen
                                    Deiner Charlees wird ihm dieser Text angezeigt</p>
                            {% endif %}
                        </blockquote>
                    </div>
                </div>
            </div>
            {% endcomment %}


            <section id="product-list">
                {% if profile.product_set %}
                    <div class="container product-wrapper">
                        <h1>Deine Produkte</h1>
                        {% for product in profile.product_set.all %}
                            <div class="container">
                                <div class="cover">
                                    <div class="row">
                                        {% if product.type == 'BK' %}
                                            <div class="col-sm-2"><i class="fa fa-bicycle fa-4x" aria-hidden="true"></i>
                                            </div>
                                        {% elif product.type == 'EL' %}
                                            <div class="col-sm-2">#</div>
                                        {% elif product.type == 'CA' %}
                                            <div class="col-sm-2">#</div>
                                        {% else %}
                                            <div class="col-sm-2"></div>
                                        {% endif %}
                                        <div class="col-sm-7">
                                            {{ product.key }}
                                        </div>
                                        <div class="col-sm-3">
                                            <p>actions</p>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        {% endfor %}
                        <div class="add-btn">
                            <form action="{% url 'product_create' %}">
                                <button type="submit" class="btn btn-info add-btn-btn">Neues Produkt registrieren</button>
                            </form>
                        </div>
                    </div>
                {% endif %}
            </section>
{% endblock %}

profiles/templates/profiles/profile_form_update.html
{% extends parent_template|default:"profiles/base_profiles.html" %}

{% block title %}
{{ block.super }} - Update Profile
{% endblock %}


{% block content %}
  <div class="row">
    <div class="offset-by-two eight columns">
      <form
          action="{{ profile.get_update_url }}"
          method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">
          Update Profile</button>
      </form>
    </div>
  </div>
{% endblock %}